version: '3.4'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
    - ".:/plugin"
  shellcheck:
    image: koalaman/shellcheck:v0.7.0
    volumes:
    - ".:/mnt"
    command:
    - ./lib/shared.bash
    - ./hooks/pre-command
    - ./hooks/post-command
