name: Cache
description: Restore and Save directories with sha256sum and s3
author: https://github.com/chef
requirements:
  - aws
  - tar
configuration:
  properties:
    cached_folders:
      type: [ array ]
  additionalProperties: false
