#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_CACHE_DEBUG:-false}" =~ (true|on|1) ]] ; then
  set -x
fi

if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then

  echo "--- :aws: Saving Cache: ${BUILDKITE_PLUGIN_CACHE_CACHE_KEY}"
  
  paths=()
  
  if [[ -n "${BUILDKITE_PLUGIN_CACHE_PATHS:-}" ]] ; then
    paths+=("$BUILDKITE_PLUGIN_CACHE_PATHS")
  fi
  
  while IFS='=' read -r path _ ; do
    if [[ $path =~ ^(BUILDKITE_PLUGIN_CACHE_PATHS_[0-9]+) ]] ; then
      paths+=("${!path}")
    fi
  done < <(env | sort)
  
  if [ "${#paths[@]}" -eq 1 ]; then

    echo "--- syncing ${paths[*]}"

  elif [ "${#paths[@]}" -gt 1 ]; then

    for path in "${paths[@]}"
      do
        echo "--- syncing ${paths}"
      done
  fi
  
fi
