#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_CACHE_DEBUG:-false}" =~ (true|on|1) ]] ; then
  set -x
fi

if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then

  cache_key="${BUILDKITE_PLUGIN_CACHE_CACHE_KEY}"

  echo ":aws: :amazon-s3: Syncing ${cache_key}"
  

  
  
  
  
  
  
fi
