#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_CACHE_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

echo "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY}"

